
version: '3.7'
services:
    frontend:
        image: angular
        ports:
            - "4200:4200"
        volumes:
            - ./frontend:/usr/src/app
        environment:
            - NODE_ENV=development
            - NODE_PORT=4200
            - NODE_HOST=node
        depends_on:
            - backend
    backend:
        image: node
        ports:
            - "3000:3000"
        volumes:
            - ./backend:/usr/src/app
        environment:
            - NODE_ENV=development
            - NODE_PORT=3000
        depends_on:
            - database
    database:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=my_user
            - MONGO_INITDB_ROOT_PASSWORD=my_password
            - MONGO_INITDB_DATABASE=my_database
    